---
- name: Install required packages
  yum:
    name:
      - git
      - curl
    state: latest

- name: add repo nodejs 
  shell: |
    curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: add repo yarn 
  shell: |
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
    rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg


- name: Install yarn, nodejs
  yum: 
    name:
      - nodejs
      - yarn
    state: latest