---
- hosts: "{{ host_name }}"
  become: yes
  become_user: root
  vars:
    dest: "/var/www/site"
    
    ansible_ssh_private_key_file: "/var/lib/jenkins/longtt.pem"    
    ansistrano_deploy_to: "{{ dest }}"
    ansistrano_deploy_from: "{{ playbook_dir }}/" # Where my local project is (relative or absolute path)
    ansistrano_keep_releases: 3

    ansistrano_deploy_via: "git"
    ansistrano_git_repo: https://github.com/issaafalkattan/react-landing-page-template-2021.git
    ansistrano_git_branch: 'main'
    # ansistrano_git_repo_tree: 'html'

    ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/before-setup-tasks.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/after-symlink-tasks.yml"

  roles:
     - { role: ansistrano.deploy }
